### ISSUE TITLE
Add build checks in CI

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/amazon-cloudwatch-agent-test#22]
There aren't any gates to ensure that the integration test code here actually builds, neither in raised PRs nor on merges to main. We should add GitHub actions on push to main and on PR submissions to make sure that the code compiles. 

This will likely involve adding a `build` target in the Makefile to run `go build` on each of the directories in the repo to ensure that they build successfully

**Comment by williazz** [comment]
I can take a look at this when I'm done with NetStat and Disk

**Comment by williazz** [comment]
Another problem is that the tests take a really long time. Would it be a good idea to just run the agent for 60 seconds with all of the configs, and then test all the metrics in one go?
